SELECT DISTINCT
    "DATE_SQL",
    "DATE_SAP",
    "DAY_OF_WEEK",
    "CALWEEK",
    "CALMONTH",
    "CALQUARTER",
    "YEAR",
    d."_DESCRIPTION" "DayName",
    q."_DESCRIPTION" "QuarterName",
    m."_DESCRIPTION" "MonthName"
FROM "SAP.TIME.VIEW_DIMENSION_DAY" td
LEFT JOIN "SAP.TIME.M_TIME_DIMENSION_TDAY" d
ON td."DAY_INT" = d."ID" AND d."_LANGU" = 'en'
LEFT JOIN "SAP.TIME.M_TIME_DIMENSION_TQUARTER" q
ON td."QUARTER" = q."ID" AND q."_LANGU" = 'en'
LEFT JOIN "SAP.TIME.M_TIME_DIMENSION_TMONTH" m
ON td."MONTH" = m."ID" AND m."_LANGU" = 'en'